<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-01-21 14:32

$extensionPath = t3lib_extMgm::extPath('t3we_youtube');
return array(
	'tx_t3weyoutube_cobj' => $extensionPath . 'class.tx_t3weyoutube_cobj.php',
	'tx_t3weyoutube_getxmldata' => $extensionPath . 'class.tx_t3weyoutube_getxmldata.php',
	'tx_t3weyoutube_lib' => $extensionPath . 'class.tx_t3weyoutube_lib.php',
);
?>